version: "3"

services:
  samarkand-web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8080:80

  samarkand-app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  samarkand-db:
    image: mysql:5
    environment:
      - MYSQL_USER=samarkand
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=samarkand
      - MAIL_ENCRYPTION=null
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

  samarkand-redis:
    image: redis:4-alpine
    ports:
      - 6379:6379

  samarkand-mail:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025

volumes:
  ? appdata
  ? dbdata
