version: '3'

services:
  samarkand-web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
    - 8080:80

  samarkand-app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=samarkand-db
      - DB_DRIVER=mysql
      - DB_DATABASE=samarkand
      - DB_USERNAME=samarkand
      - DB_PASSWORD=secret

  samarkand-db:
    image: mysql:5
    environment:
      - MYSQL_USER=samarkand
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=samarkand
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  appdata:
  dbdata:
